Feat/8/create app base
CATechAccel/CATechDojo pull request #10
Opened 2020-12-01 18:34 UTC by sne-5249

## Issue8

close #8 

## タスク整理

- [ ] DBへの接続
- [ ] HTTPサーバの作成
- [ ] MVCでの切り分け

## 学んだこと

- HTTPメソッドの指定方法（gorilla/muxパッケージを利用）
> １、*Router型の変数を定義
```go
r := mux.NewRouter()
```
> ２、Methodsメソッドを利用して、HTTPメソッドを指定
```go
r.Methods("GET")
```

- エラー処理では、呼び出し元にエラーを返す
ハンドラのエラー処理では、`http.Error()`を利用する

- MVCでの切り分けにより責務の分離を行う（->進化するとMVCS）
> モデル：DB関係の処理
> コントローラ：ルーターからの処理

## 補足事項

2020-12-01 23:50 UTC, Takumaron commented
PullRequestのタイトルの修正をよろしく！！

2020-12-02 00:01 UTC, Takumaron requested changes
interfaceとポインタレシーバ使ってみよう！という課題を出したけれど，ちょっとやってみて分からなそうだったら声かけてね！

2020-12-02 00:01 UTC, TakumaKurosawa commented on model/user/user.go
> +}
ここの構造体定義を`model/user/userentity`に移してあげても良いかもね！

2020-12-02 00:01 UTC, Takumaron commented on model/user/user.go
> +func SelectAllUser() ([]UserData, error) {
[TRY]
`UserData`構造体をポインタレシーバーに取ってあげてもいいかもね！？
かつ，interfaceを使ってこのmodel.userパッケージで必要な関数を定義しておくと良いかも！

2020-12-02 01:11 UTC, sne-5249 commented on model/user/user.go
> +}
わかりやすくなりますね！移動しました！

2020-12-03 03:17 UTC, Takumaron approved these changes
LGTM!
表記ゆれの部分だけ修正してからマージしてください！

2020-12-03 03:17 UTC, Takumaron commented on model/user/user.go
> +	UpdateUserData(UserData) (UserData, error)
`User`か`UserData`はどちらかに名前を統一しよう!

2020-12-03 04:26 UTC, sne-5249 commented on model/user/user.go
> +	UpdateUserData(UserData) (UserData, error)
修正しました！

2020-12-03 04:26 UTC, merged