ユーザアカウント認証情報作成APIの実装
CATechAccel/CATechDojo pull request #11
Opened 2020-12-04 00:44 UTC by sne-5249

## Issue2

close #2

## タスク整理

- [ ] ユーザの名前情報をリクエストで受け取る
- [ ]  ユーザidの生成
- [ ]  トークンの生成
- [ ]  DBへの保存

## 学んだこと

- エラーハンドリングの中身
関数やメソッドでは、エラーを呼び出し元に返しす処理を行う
```go
if err != nil {
	return err
}
```
　　ハンドラでは、エラーを表示させる処理を実装する
```go
if err != nil {
	log.Println(err)　//※
	http.Error(w, err.Error(), http.StatusInternalServerError)
}
```
※エラー処理では、ユーザへのエラーの表示の他に開発者側にどこでエラーが起きているかを残すlogの表示を行う必要がある。

- uuidパッケージ：ランダムな（確率的にほとんどかぶることがない）文字列の生成に利用する
https://hawksnowlog.blogspot.com/2019/04/generate-uuid-with-golang.html

- バリデーション ：ユーザからの入力が適切かをチェックする

-グローバルな関数/変数は**上**に、ローカルな関数/変数は**下**に記述する

## 補足事項

2020-12-05 02:17 UTC, Takumaron commented
>-グローバルな関数/変数は上に、ローカルな関数/変数は下に記述する

ごめん！伝え方が間違っていたのだけれど， **グローバルな関数は上に，ローカルな関数は下に** が正しいかな！
基本的に変数や形定義は上に書くのでお間違いなく:pray:

2020-12-05 02:24 UTC, Takumaron requested changes
DRY意識していこう！

2020-12-05 02:24 UTC, Takumaron commented on controller/user/user.go
> +}
```suggestion
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
	_, _ = w.Write(data)
}
```

2020-12-05 02:24 UTC, Takumaron commented on controller/user/user.go
>  }
ここの処理の内容って完全に被っているよね？
こういうおんなじ記述がある場合に重複を排除しようという考え方が，DRYっていうんだけど，今回の場合だと，もうちょっと抽象度を上げてあげて，`createUUID`みたいな関数名にしてあげれば，1つの関数としてまとめられそうだね！

プログラミングの原則的な話は結構ネットに書かれていたりするから，読んでみると良いかも！
https://qiita.com/hirokidaichi/items/d6c473d8011bd9330e63

2020-12-05 02:24 UTC, Takumaron commented on controller/user/user.go
> +}
これそのまま`commit suggestion`してもらえればOKです！
変更点としては，余分な改行消しただけなので！

2020-12-06 13:16 UTC, sne-5249 commented
@Takumaron 
承知しました！ありがとうございます🙇‍♀️
学んだことの記述の修正doneです。

2020-12-06 13:22 UTC, sne-5249 commented on controller/user/user.go
>  }
確かに、そうですね、、、！
CreateUUIDとして修正してみました！

ありがとうございます、読んでみます🙇‍♀️

2020-12-07 15:20 UTC, Takumaron approved these changes
LGTM!

2020-12-07 15:21 UTC, merged