ユーザ情報取得APIの実装
CATechAccel/CATechDojo pull request #12
Opened 2020-12-06 13:03 UTC by sne-5249

## Issue3

close #3

## タスク整理

 - [ ] ヘッダーの中身の取り出し
 - [ ] 該当データの取り出し
 - [ ] 取得したデータの返信

## 学んだこと

- ヘッダーの中身の取得方法
func handler(w http.ResponseWriter, r *http.Request){
   r.Header.Get("key")
}

- 特定のデータを取得するSQL文
SELECT * FROM user WHERE カラム名 = 値

- Scan関数では、取得したデータ全てをマッピングしなければならない

## 補足事項

2020-12-07 15:36 UTC, Takumaron requested changes
ユーザ全件取得APIはSwaggerにはないけど、別に消さなくちゃならないわけじゃないからコードとして残しておいてあげてもいいじゃないかな？

コンフリクトの解決もとても良い機会なので是非挑戦してみて！

2020-12-07 15:36 UTC, Takumaron commented on main.go
> +	r.HandleFunc("/user/get", user.GetUser).Methods("GET")
GetAllUserハンドラはそのまま残してもいいんじゃないかな？

2020-12-07 15:36 UTC, Takumaron commented on controller/user/user.go
> +	token := r.Header.Get("x-token")
tokenが空だったらエラーにするバリデーションを追加しよう！

2020-12-07 15:36 UTC, Takumaron commented on model/user/user.go
> +func (u *UserData) SelectUser(token string) (*UserData, error) {
実は、構造体にマッピングした時点でポインタレシーバ自体の値が変わっているはずだから`*UserData`を返却してあげる必要はないね！

2020-12-08 08:52 UTC, sne-5249 commented on model/user/user.go
> +func (u *UserData) SelectUser(token string) (*UserData, error) {
そうですね、、、、！
修正しました。

2020-12-08 08:52 UTC, sne-5249 commented on main.go
> +	r.HandleFunc("/user/get", user.GetUser).Methods("GET")
GetAllUser、復活させましたー！

2020-12-09 15:32 UTC, sne-5249 commented on controller/user/user.go
> +	token := r.Header.Get("x-token")
追加してみました！

2020-12-09 17:17 UTC, Takumaron requested changes
あとちょっと！

2020-12-09 17:17 UTC, Takumaron commented on controller/user/user.go
> +		http.Error(w, "該当するユーザが存在しませんでした", http.StatusInternalServerError)
ここのエラー文は本当にこれでユーザがエラーの原因がわかるかな？

今回のバリデーションエラーは、トークンの値を送信しないといけないのに、**ユーザがミスって**送れていないというエラーだよね？

2020-12-09 17:52 UTC, sne-5249 commented on controller/user/user.go
> +		http.Error(w, "該当するユーザが存在しませんでした", http.StatusInternalServerError)
トークンが入力されていません。/トークンを入力してください。
とかが適切でしょうか、、、？

2020-12-10 01:57 UTC, Takumaron commented on controller/user/user.go
> +		http.Error(w, "該当するユーザが存在しませんでした", http.StatusInternalServerError)
トークンをユーザが直接入力するわけではないので、「認証情報が必要です。」とかが良いんじゃないかな？

2020-12-11 02:49 UTC, sne-5249 commented on controller/user/user.go
> +		http.Error(w, "該当するユーザが存在しませんでした", http.StatusInternalServerError)
確かに、、、適切ですね、、、
修正しました！

2020-12-11 04:00 UTC, Takumaron approved these changes
文言はOKそう！
このコメントであえて太字にしているところなんだけど，これはユーザのインプットがおかしくてエラーにしているエラーだから，`http.StatusInternalServerError`では意味が変わってくるね！

https://github.com/CATechAccel/CATechDojo/pull/12#discussion_r539494008
そこだけ修正したらマージしてOKです！

2020-12-11 04:44 UTC, sne-5249 commented
@Takumaron 
完全にその部分の区別を忘れてました、、
StatusBadRequestに修正しました。

2020-12-11 04:55 UTC, merged