ユーザー情報更新APIの実装
CATechAccel/CATechDojo pull request #13
Opened 2020-12-07 01:59 UTC by sne-5249

## Issue4

close #4 

## タスク整理

- [ ] リクエストの受け取り
- [ ] データの更新

## 学んだこと

- sqlパッケージを利用したアップデートのやり方
https://qiita.com/tenntenn/items/dddb13c15643454a7c3b

- データをupdateするSQL文
```
"UPDATE <テーブル名> SET <更新するカラム名> = ? WHERE auth_token = ?"
```

- HTTPメソッドまとめ
https://developer.mozilla.org/ja/docs/Web/HTTP/Methods
https://qiita.com/fukulingo/items/a9e8d18467fe3e04068e
> GET：データの取得
POST：データの作成・追加
PUT：データの更新・作成

## 補足事項

2020-12-07 16:48 UTC, Takumaron requested changes
いくつかコメントしました！

2020-12-07 16:48 UTC, Takumaron commented on controller/user/user.go
> +func ChangeUser(w http.ResponseWriter, r *http.Request) {
仕様的にはユーザ名を変えるAPIだと思っているので、`ChangeUserName`とかの方がやる事明確になりそうかなと思った！

2020-12-07 16:48 UTC, Takumaron commented on controller/user/user.go
> +	}
ユーザからのリクエストは、

```json
{
	"name": "string"
}
```

なのに、受け取っている型は`UserData`でいいのかな？？

リクエストボディをAPI毎に定義してあげた方が良い気がするので、新しくrequestパッケージ作ってみて！

2020-12-07 16:48 UTC, Takumaron commented on controller/user/user.go
> +func funcErr(err error, w http.ResponseWriter) {
funcなのに`funcErr`という名前は冗長な気がするね！
`errorResponse`とかどうでしょう？？

2020-12-07 16:48 UTC, Takumaron commented on model/user/user.go
> +func (u *UserData) UpdateUser(token string) error {
`UpdateUserName`の方が処理が明確になりそう？？

2020-12-07 16:48 UTC, Takumaron commented on model/user/user.go
> +func (u *UserData) UpdateUser(token string) error {
っ思ったけど、そもそもこれ`UserData`がポインタレシーバになっててUserに対する処理だってことは自明なので、そもそも`User`っていう文言不要な気がした！
`SelectAllUser`とかも`User`要らなそうだね！

2020-12-07 16:49 UTC, Takumaron commented
Descriptionに学んだことめちゃくちゃまとまっていて本当すごい！

2020-12-08 08:36 UTC, sne-5249 commented on controller/user/user.go
> +func funcErr(err error, w http.ResponseWriter) {
確かにそうですね！
修正しました！

2020-12-08 08:36 UTC, sne-5249 commented on model/user/user.go
> +func (u *UserData) UpdateUser(token string) error {
修正しました！

2020-12-09 16:37 UTC, sne-5249 commented on controller/user/user.go
> +	}
requestパッケージ作成し、update機能の部分を別で定義してみました。

2020-12-09 17:13 UTC, Takumaron requested changes
コメントしました！
どこに何を置くのかが難しいところだと思うけど、是非議論しながら進めていこう！

2020-12-09 17:13 UTC, Takumaron commented on model/request/update_request.go
> +}
ユーザから送られてきたデータをバインドするためだけの構造体だと思うから、このリクエストをUpdateNameのレシーバにするのはちょっと違う気がしている！

`UpdateName()`でtokenを引数に取っていると思うんだけど、それと同じように、`UpdateName(name string)`にしてみてー

この辺はアプリケーションアーキテクチャって呼ばれる領域で、Goに限らずかなり重要な感覚になってくると思うから1度話したいねー

2020-12-09 17:13 UTC, Takumaron commented on model/user/user.go
> -	UpdateUser(UserData) (UserData, error)
本来UpdateUserはこのuserパッケージ内に定義されているべきだよね。
`model/request/update_request.go`を作った理由とか聞けたら嬉しい！

2020-12-09 17:13 UTC, Takumaron commented on controller/user/user.go
>  func GetAllUser(w http.ResponseWriter, r *http.Request) {
`ChangeName`と名前揃えるなら、 `GetAll`とかかな？

2020-12-09 17:13 UTC, Takumaron commented on controller/user/user.go
> +func ChangeName(w http.ResponseWriter, r *http.Request) {
`CreateUser`とかに名前を合わせるのか、`ChangeName`に合わせるかは決めた方が統一感でそう！

2020-12-09 18:56 UTC, sne-5249 commented on controller/user/user.go
> +func ChangeName(w http.ResponseWriter, r *http.Request) {
GetAll / Create / ChangeName として、ハンドラの名前を修正しました。

2020-12-09 19:00 UTC, sne-5249 commented on model/request/update_request.go
> +}
一旦、UpdateNameメソッドをuserパッケージに戻し、更新するデータは引数で渡すように修正してみました。
ちょっと整理できていない部分もあるので、明日などにこの部分について相談させていただけるとありがたいです！🙇‍♀️

2020-12-10 01:53 UTC, Takumaron approved these changes
引数のとことRequest構造体の命名だけ修正してほしい！けど、そこ修正したら一旦マージしてOKです！

2020-12-10 01:53 UTC, Takumaron commented on model/request/update_request.go
> +}
ファイル名はモデルの単位で分けてあげた方が良いかなーと思うよ！
今回このUpdateRequestはユーザ関連APIのリクエストだと思うから、`model/request/user.go`の`UpdateNameRequest`とかが適切かなー

2020-12-10 01:53 UTC, Takumaron commented on model/user/user.go
> +	UpdateName(string, string) error
Golandでコードジャンプするとわかると思うけど、実装する人は基本的にインターフェースを見てどんな事ができるのか想像するので、引数に名前をつけておくことは重要だよ！
この状態だと、string型を2つ受け取ることはわかるけど、それ以上の情報がないかな！

2020-12-10 01:53 UTC, Takumaron commented on controller/user/user.go
> +	if err := u.UpdateName(reqBody.Name, token); err != nil {
ここは引数で与えてもいいし、下記のようにUserDataにマッピングしてあげても良いよ！
```suggestion
	var u user.UserData
	u.Name = reqBody.Name
	if err := u.UpdateName(token); err != nil {
```

2020-12-10 01:55 UTC, Takumaron commented on model/request/update_request.go
> +type UpdateRequest struct {
ごめん！見落としていたけど、パッケージ構成ちょっとこれだとまずいかも！
ユーザとのやりとりの入り口（Request）と出口（Response）が関心ごとなのに、モデルのなかに定義されちゃってると意味が変わってきそう。

2020-12-11 02:40 UTC, sne-5249 commented on controller/user/user.go
> +	if err := u.UpdateName(reqBody.Name, token); err != nil {
修正しました！

2020-12-11 02:40 UTC, sne-5249 commented on model/request/update_request.go
> +type UpdateRequest struct {
ほんとですね、、、コントローラーに移動しました！

2020-12-11 02:42 UTC, sne-5249 commented on model/request/update_request.go
> +}
ファイル名・構造体名を、`model/request/user.go` `UpdateNameRequest`に修正しました！

2020-12-11 02:44 UTC, sne-5249 commented on model/user/user.go
> +	UpdateName(string, string) error
なるほど、そうですね！
nameはレシーバで受け取るように変更したので、tokenの方だけ名前つけました。

2020-12-11 04:41 UTC, merged