ガチャ実行APIの作成
CATechAccel/CATechDojo pull request #17
Opened 2021-01-06 14:49 UTC by sne-5249

## Issue6

close #6

## タスク整理

- [ ] サンプルキャラクターの作成
- [ ] ガチャパッケージの作成
- [ ] ランダムにキャラクターを取得する処理を実装
- [ ] 取得したキャラクターをDBヘ保存する処理を実装
- [ ] キャラクター別にガチャの確率を分ける

## 学んだこと

## 補足事項

2021-01-19 08:08 UTC, kznrluk approved these changes

2021-01-19 08:34 UTC, Takumaron requested changes

2021-01-19 08:34 UTC, TakumaKurosawa commented on controller/gacha/gacha.go
> +	"time"
あれ？goimports効いてる？？

2021-01-19 08:34 UTC, TakumaKurosawa commented on controller/gacha/gacha.go
> +func DrawSpecificCharacter(w http.ResponseWriter, r *http.Request) {
`DrawCharacter`で良い気がする．

```suggestion
func DrawCharacter(w http.ResponseWriter, r *http.Request) {
```

2021-01-19 08:34 UTC, TakumaKurosawa commented on controller/gacha/gacha.go
> +	if err := g.SelectCharacter(); err != nil {
```suggestion
	g := gacha.New()
	if err := g.SelectCharacter(); err != nil {
```

2021-01-19 08:34 UTC, TakumaKurosawa commented on controller/gacha/gacha.go
> +	userCharacterID, err := user.CreateUUID()
`CreateUUID`という便利機能は`user`パッケージにあると，こういう時に「なんでキャラクターのこと扱っているのに`user`パッケージなんだろ？って疑問に思うと思うので，`util`パッケージみたいなモノに切り出してあげた方が良いと思う！

2021-01-19 08:34 UTC, Takumaron commented on controller/gacha/gacha.go
> +		http.Error(w, "ユーザデータを保存できませんでした", http.StatusInternalServerError)
「ユーザデータ」になっている！

2021-01-19 08:34 UTC, Takumaron commented on controller/gacha/gacha.go
> +func Draw(w http.ResponseWriter, r *http.Request) {
`DrawSpecificCharacter()`とは別という認識？？

2021-01-19 08:34 UTC, Takumaron commented on controller/gacha/gacha.go
> +	odds, err := g.SelectAllOdds()
```suggestion
	g := gacha.New()

    //gacha_oddsテーブルから全件取得
	odds, err := g.SelectAllOdds()
```

2021-01-19 08:34 UTC, Takumaron commented on controller/gacha/gacha.go
> +	rand.Seed(time.Now().UnixNano())
急に乱数生成用の初期化処理が入るとびっくりするから，コメント入れたりしよう！

2021-01-19 08:34 UTC, Takumaron commented on controller/gacha/gacha.go
> +	for i := 1; i <= times.Times; i++ {
`i=1`とするのは結構トリッキーなので，`i=0`から始まるfor文に修正しよう！

```suggestion
	for i := 0; i < times.Times; i++ {
```

2021-01-19 08:34 UTC, Takumaron commented on controller/gacha/gacha.go
> +		for i, _ := range odds {
```suggestion
		//当選キャラクターの決定
		var count int
		for i, _ := range odds {
```

2021-01-19 08:34 UTC, Takumaron commented on controller/gacha/gacha.go
> +			h := odds[i].CharacterID
`h`っていう変数名が何を表すのかわからないので，ちゃんと命名してあげたい！

2021-01-19 08:34 UTC, Takumaron commented on controller/gacha/gacha.go
> +			hitCharacterID = h
これ必要かな？？

2021-01-19 08:34 UTC, Takumaron commented on controller/gacha/gacha.go
> +		userCharacterID, err := user.CreateUUID()
上と同じです！

2021-01-19 08:34 UTC, Takumaron commented on controller/gacha/gacha.go
> +		}
ここはAPI実装が完了したタイミングでお話しする予定の`N+1問題`になっているね！
TODOコメントで「N＋1問題」みたいに入れておいてもらえると！

2021-01-19 08:34 UTC, Takumaron commented on controller/gacha/gacha.go
> +	var hitCharacterslice response.DrawAllResponse
```suggestion
	var hitCharacterSlice response.DrawAllResponse
```

2021-01-19 08:34 UTC, Takumaron commented on controller/response/gacha.go
> +type DrawResponse struct {
`DrawResult`みたいな名前にすれば，`DrawAllResponse`っていう名前じゃなくできそうじゃない？？

2021-01-19 08:34 UTC, Takumaron commented on controller/user/user.go
> +func CreateUUID() (string, error) {
`user`パッケージ内にUUIDを作成する関数は不要かなー

2021-01-19 08:34 UTC, Takumaron commented on main.go
> +	r.HandleFunc("/gacha/drawspecific", gacha.DrawSpecificCharacter).Methods("GET")
これは仕様に無い気がする！

2021-01-19 08:34 UTC, Takumaron commented on model/gacha/gacha.go
> +}
これはあんまりよろしく無いかなー．
モデル層からAPIのレスポンスに関する知識を持ち込みたく無いかなー

2021-01-19 08:34 UTC, Takumaron commented on model/gacha/gacha.go
> +	}
`InsertCharacter`という関数名なのに，SELECTしているので，めちゃくちゃ怖い関数になっている！

2021-01-19 08:34 UTC, Takumaron commented on model/gacha/gacha.go
> +	}
ここもInsertなのにSELECT使っている！

2021-01-19 09:59 UTC, sne-5249 commented on controller/gacha/gacha.go
> +	"time"
すみません、どういうことでしょうか、、、？

2021-01-19 10:00 UTC, sne-5249 commented on controller/gacha/gacha.go
> +	if err := g.SelectCharacter(); err != nil {
修正しました！

2021-01-19 10:02 UTC, sne-5249 commented on controller/gacha/gacha.go
> +	userCharacterID, err := user.CreateUUID()
確かに、いろいろ混同してしまっていてだいぶわかりにくいですね、、、
とりあえず、CreateUUIDは切り分けました！
先ほどDiscordで教えていただいた他の部分の修正もこれからやろうと思います。

2021-01-19 10:02 UTC, sne-5249 commented on controller/gacha/gacha.go
> +		http.Error(w, "ユーザデータを保存できませんでした", http.StatusInternalServerError)
修正しました！

2021-01-19 10:02 UTC, sne-5249 commented on controller/user/user.go
> +func CreateUUID() (string, error) {
utilパッケージに切り分けましたー！

2021-01-19 10:03 UTC, sne-5249 commented on main.go
> +	r.HandleFunc("/gacha/drawspecific", gacha.DrawSpecificCharacter).Methods("GET")
ひとまずハンドラのみ削除しました！

2021-01-19 10:08 UTC, Takumaron commented on controller/gacha/gacha.go
> +	"time"
一旦忘れてOK!

2021-01-19 10:10 UTC, sne-5249 commented on controller/gacha/gacha.go
> +func DrawSpecificCharacter(w http.ResponseWriter, r *http.Request) {
修正しました！
この処理は、仕様書にはなくハンドラを削除したのですが、この処理自体も削除してしまったほうがいいでしょうか？

2021-01-19 10:10 UTC, sne-5249 commented on controller/gacha/gacha.go
> +	"time"
承知しましたー！

2021-01-19 10:11 UTC, Takumaron commented on controller/gacha/gacha.go
> +func DrawSpecificCharacter(w http.ResponseWriter, r *http.Request) {
削除してしまって欲しいです！

2021-01-19 10:12 UTC, sne-5249 commented on controller/gacha/gacha.go
> +func DrawSpecificCharacter(w http.ResponseWriter, r *http.Request) {
分かりました！ありがとうございます🙇‍♀️

2021-01-19 10:21 UTC, sne-5249 commented on model/gacha/gacha.go
> +}
修正の内容としては、
①モデルでそれぞれCharacterIDとNameを取り出すメソッドを定義する
②コントローラでresponse.DrawResponse型の構造体に値を入れる
という感じでしょうか？

(削除したDrawCharacterで使用していたので、このメソッド自体は削除してしまっているため、修正の内容だけ確認させていただきたいです。)

2021-01-19 10:25 UTC, Takumaron commented on model/gacha/gacha.go
> +}
`*GachaData`自体はポインタレシーバになっているはずなので，コントローラから利用するときは`g`自体を参照すれば良いという実装にしておけば良いね！

2021-01-19 10:44 UTC, sne-5249 commented on model/gacha/gacha.go
> +}
```Go
#model
func (g *GachaData) GetCharacterID() string {
    return g.CharacterID
}

func (g *GachaData) GetName() string {
    return g.Name
}
```
```Go
#controller
res := response.DrawResponse{
    CharacterID: g.GetCharacterID(),
    Name:        g.GetName(),
}
```
何度もすみません🙇‍♀️
こういった形での修正とは、また違うでしょうか、、、？
これはg自体の参照ではないですよね、、、

2021-01-19 10:47 UTC, Takumaron commented on model/gacha/gacha.go
> +}
モデル側に`GetCharacterID()`や`GetName()`を用意しなくても，ポインタレシーバを用いているので，Controllerから直接値が参照できるよね！
ただ，オブジェクト指向としては，かねぽんが書いてくれたようなアクセサメソッド（`GetCharacterID()`など）を用意するのが正解なので，どの思想を採用するかで考えれば良いと思う！
今回の場合，確かUserモデルの方とかで直接参照する形をとっていたと思うので，そちらと合わせたいなと思っています．

2021-01-19 10:57 UTC, sne-5249 commented on model/gacha/gacha.go
> +}
gが
```Go
g := character.New()
```
で定義されているインターフェースだからアクセサメソッドを使わないといけないみたいなのはまた違う感じでしょうか、、、、？

2021-01-19 11:19 UTC, Takumaron commented on model/gacha/gacha.go
> +}
あ！そうやった！
やから，どちらにせよかねぽんが提示してくれたアクセサメソッド実装して取得する必要があるのか！

2021-01-19 11:40 UTC, sne-5249 commented on model/gacha/gacha.go
> +}
承知しました！
納得できました！ありがとうございます🙇‍♀️

2021-01-19 11:41 UTC, sne-5249 commented on model/gacha/gacha.go
> +	}
SelectUserIDとして切り分けました！

2021-01-20 04:31 UTC, Takumaron commented on controller/gacha/gacha.go
> +	rand.Seed(time.Now().UnixNano())
@sne-5249

2021-01-20 04:31 UTC, Takumaron commented on controller/gacha/gacha.go
> +	for i := 1; i <= times.Times; i++ {
@sne-5249

2021-01-20 04:32 UTC, Takumaron commented on controller/gacha/gacha.go
> +		for i, _ := range odds {
@sne-5249

2021-01-20 05:32 UTC, sne-5249 commented on controller/gacha/gacha.go
> +		http.Error(w, "ユーザデータを保存できませんでした", http.StatusInternalServerError)
すみません、ユーザデータをユーザーデータにすることかと思ってしまってました🙇‍♀️
キャラクターデータに修正しました。

2021-01-20 05:33 UTC, sne-5249 commented on controller/gacha/gacha.go
> +	if err := g.SelectCharacter(); err != nil {
すみません、こちらもDrawCharacterの方のみ修正して、Drawで修正忘れてました🙇‍♀️💦
Drawの方の改行も削除しました。

2021-01-20 05:34 UTC, sne-5249 commented on model/gacha/gacha.go
> +	}
これは、仕様書にない処理として削除させていただきました🙇‍♀️

2021-01-20 05:58 UTC, sne-5249 commented on controller/gacha/gacha.go
> +	rand.Seed(time.Now().UnixNano())
コメント入れました！

2021-01-20 05:59 UTC, sne-5249 commented on controller/gacha/gacha.go
> +	for i := 1; i <= times.Times; i++ {
はい！修正しました。

2021-01-20 06:03 UTC, sne-5249 commented on controller/gacha/gacha.go
> +			hitCharacterID = h
必要じゃないですね、、、
修正しました！

2021-01-20 06:16 UTC, sne-5249 commented on controller/response/gacha.go
> +type DrawResponse struct {
なるほど！そうですね！
ありがとうございます。

2021-01-20 10:14 UTC, Takumaron commented on controller/gacha/gacha.go
> +	rand.Seed(time.Now().UnixNano())
@sne-5249 
ん？コメント入ってないっぽいよー？

2021-01-20 10:14 UTC, Takumaron commented on controller/gacha/gacha.go
> +			h := odds[i].CharacterID
@sne-5249

2021-01-20 10:15 UTC, Takumaron commented on controller/gacha/gacha.go
> +			hitCharacterID = h
修正されてないっぽいよー

2021-01-20 10:19 UTC, Takumaron approved these changes
修正が完了していない2点だけ実装してマージしてOKです！

2021-01-20 12:37 UTC, sne-5249 commented on controller/gacha/gacha.go
> +			hitCharacterID = h
あああ、何度もすみません🙇‍♀️
ローカルでの修正をpushする前に、git上での修正を反映させなければとpullしてしまったために、conflictがおきた時に、修正部分が消えてしまってました、、、💦

2021-01-20 12:39 UTC, merged