ユーザ所持キャラクター一覧取得APIの実装
CATechAccel/CATechDojo pull request #18
Opened 2021-01-20 07:22 UTC by sne-5249

## Issue7

close #7

## タスク整理

- [ ] user_characterテーブルから特定のユーザーが所持しているユーザーキャラクターidとキャラクターのidを取得
- [ ] キャラクターidから、該当するキャラクターの名前を取得
- [ ] userCharacterID, CharacterID, Nameをフィールドとして持つストラクトを持つcharacter配列をレスポンスとして返す

## 学んだこと

## 補足事項

2021-01-20 10:39 UTC, Takumaron requested changes
自分なりに処理を小さなまとまりになるように分けてくれたんだね！
直接話して，今の分け方が抱えている問題点とか一緒に考えたいと思うので，Discordつないで話しましょう！

あと，基本的にDraftではない状態でコードレビューをしてもらう＝プロダクションに乗せても問題ないコードですよという意味になってしまうので，もし実装途中の状態で2割当てしたいという意図があるなら，PRをDraftにした状態でレビューを依頼しよう！（現状のコードだと，エラーハンドリングのところとか`fmt.Println()`してるだけになってたりするよ！）

[TODO]
一旦ここまで書いてくれたコードをコメントアウトして，`user`パッケージや`gacha`パッケージと同じような実装方法で機能を作成してほしいです！

2021-01-20 10:39 UTC, Takumaron commented on controller/characters/character.go
> +package characters
userパッケージに合わせて，単数形に名前を変更してあげよう！

2021-01-20 10:39 UTC, Takumaron commented on model/characters/character.go
> +package characters
userパッケージと合わせて単数形にしましょう！

2021-01-20 10:39 UTC, Takumaron commented on controller/characters/character.go
> +func Show(w http.ResponseWriter, r *http.Request) {
userパッケージの方では，`GetUser()`みたいな命名にしているはずなので，そちらと合わせた方が統一性が出そう．

2021-01-20 13:50 UTC, sne-5249 commented
パッケージ名、関数名の修正行いました！
[TODO]も完了しましたが、gitにあげたらいいでしょうか？

2021-01-20 14:17 UTC, Takumaron commented
> パッケージ名、関数名の修正行いました！
> [TODO]も完了しましたが、gitにあげたらいいでしょうか？

@sne-5249 
うん、上げて欲しい！

2021-01-22 05:36 UTC, Takumaron requested changes
コメントしました！

2021-01-22 05:36 UTC, Takumaron commented on controller/response/character.go
> +	Characters []character.UserCharacterData `json:"character"`
model層の実装を`response`パッケージが知ってしまっている状態は避けたいかなー・・・
詳しくはPospomeさんの買ってもらった書籍に書いてあるんだけど，基本的にMVCモデルっていうのは依存関係が，Model→Controller→Viewになっているので，ControllerからModelに対する参照は基本的にNGです🙅‍♂️

2021-01-22 05:36 UTC, Takumaron commented on model/character/character.go
> +}
`users`テーブルに関する処理なのに，`character`パッケージに書くのは実装的にNGです！
実装としては，`character`コントローラから`user`モデルと`userCharacter`モデルと，`character`モデルを用いてユーザの所持しているキャラクター一覧を取得するという実装になるはず！

2021-01-22 05:36 UTC, Takumaron commented on model/character/character.go
> +}
この実装は`user_characters`テーブルに対する操作だから，このパッケージにあってOKです！🙆‍♂️

2021-01-22 05:36 UTC, Takumaron commented on model/character/character.go
> +}
この実装も本来は`character`モデルに実装するべき実装だね！

2021-01-22 05:36 UTC, Takumaron commented on controller/character/character.go
> +	}
本来は，`user`モデルを利用してどのユーザかを特定するべきです！

2021-01-22 05:36 UTC, Takumaron commented on controller/character/character.go
> +	}
本来は，`user_character`モデルを用いて実装するべきです！

2021-01-22 05:36 UTC, Takumaron commented on controller/character/character.go
> +	for _, u := range userCharacters {
個人的には，`u`とか分かりにくい変数名は慣例的な `for i:=0;i<x;i++`などのようなコード以外で出さない方が良いと思っている派なので，ちゃんと命名したいです！

2021-01-22 05:36 UTC, Takumaron commented on controller/character/character.go
> +		characterName, err := c.SelectCharacterName(u.CharacterID)
ここで出てくる`u.CharacterID`というものが，読む人からすると

>u=userだと思っていたのに，いきなりCharacterIDって出てきたからuserじゃなかったのか！！

って驚く実装になっています．
上でも書いた通り，変数名には気を遣いましょう！

2021-01-23 14:10 UTC, Takumaron approved these changes
LGTM

2021-01-23 14:10 UTC, merged